### ISSUE TITLE
Better errors?

### ISSUE THREAD

**Issue by danigb** [diegohaz/schm#42]
Hi, 

First of all, thanks for the library. I'm testing it against a new project and looks promising.

But I found something not very intuitive. Having this code:

```js
const s = schema({
  age: { type: Number, required: true }
});
s.validate({ age: 'not-a-number' }) // => [ { param: 'age', message: 'age is required' }]
```

IMHO the message should be "age is not a number" because the age is provided (but not in the correct form)

What do you think?

**Comment by diegohaz** [comment]
Hey, @danigb. Thanks for the feedback.

Since this library follows mongoose schemas spec, `type` isn't a validator. It's a parser, which means that if you pass a value of another type, it'll try to cast it to the type you set in the schema.

Here I explain how you can create a `typeof` validator: https://github.com/diegohaz/schm/issues/33#issuecomment-376542488

**Comment by danigb** [comment]
Hey, @diegohaz. Thanks for the response! (and sorry for my delay)

Yes, now I understand about the mongodb compatibility, but here are my thoughts:

1) I find it counterintuitive: when I specify a `type` in a schema library I expect to validate that type (not only to convert to that type)
2) I think the `typeof` validator should be baked in into the core
3) I couldn't find a list of available validators inside any README file, and I think that's one of the first things I look for in a schema library. I could do a PR for that if you agree.

Anyway, thanks for the library! 👏

**Comment by danigb** [comment]
And I have another problem with your solution: currently, I'm using the `query` function of [schm-express](https://github.com/diegohaz/schm/blob/master/packages/schm-express), but I don't know how (or if it's possible) to add the type validator.

**Comment by diegohaz** [comment]
The reason I didn't add docs around validators and parsers was because they are pretty the same as the ones of Mongoose. But I'd really appreciate a PR adding them to the docs. :)

You can pass the object you create with `schema` to `query`. So, if you have a `typeof` validator there, it'll work within `query` too.
